<?php

use Illuminate\Database\Seeder;

class IconTableSeeder extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        $icon = [
            [
                "menu_icon_name" => "Emo Happy",
                "menu_icon_class" => "emo-happy",
                "menu_icon_unicode" => "&#xe802;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Emo Wink",
                "menu_icon_class" => "emo-wink",
                "menu_icon_unicode" => "&#xe803;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Emo Wink 2",
                "menu_icon_class" => "emo-wink-2",
                "menu_icon_unicode" => "&#xe823;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Emo Unhappy",
                "menu_icon_class" => "emo-unhappy",
                "menu_icon_unicode" => "&#xe824;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Emo Sleep",
                "menu_icon_class" => "emo-sleep",
                "menu_icon_unicode" => "&#xe825;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Emo Thumbsup",
                "menu_icon_class" => "emo-thumbsup",
                "menu_icon_unicode" => "&#xe86e;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Emo Devil",
                "menu_icon_class" => "emo-devil",
                "menu_icon_unicode" => "&#xe829;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Emo Surprissed",
                "menu_icon_class" => "emo-surprissed",
                "menu_icon_unicode" => "&#xe82a;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Emo Tongue",
                "menu_icon_class" => "emo-tongue",
                "menu_icon_unicode" => "&#xe82b;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Emo Coffee",
                "menu_icon_class" => "emo-coffee",
                "menu_icon_unicode" => "&#xe82c;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Emo Sunglass",
                "menu_icon_class" => "emo-sunglass",
                "menu_icon_unicode" => "&#xe82d;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Emo Displeased",
                "menu_icon_class" => "emo-displeased",
                "menu_icon_unicode" => "&#xe82e;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Emo Beer",
                "menu_icon_class" => "emo-beer",
                "menu_icon_unicode" => "&#xe82f;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Emo Grin",
                "menu_icon_class" => "emo-grin",
                "menu_icon_unicode" => "&#xe862;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Emo Angry",
                "menu_icon_class" => "emo-angry",
                "menu_icon_unicode" => "&#xe863;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Emo Saint",
                "menu_icon_class" => "emo-saint",
                "menu_icon_unicode" => "&#xe864;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Emo Cry",
                "menu_icon_class" => "emo-cry",
                "menu_icon_unicode" => "&#xe865;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Emo Shoot",
                "menu_icon_class" => "emo-shoot",
                "menu_icon_unicode" => "&#xe866;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Emo Squint",
                "menu_icon_class" => "emo-squint",
                "menu_icon_unicode" => "&#xe867;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Emo Laugh",
                "menu_icon_class" => "emo-laugh",
                "menu_icon_unicode" => "&#xe868;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Spin 1",
                "menu_icon_class" => "spin-1",
                "menu_icon_unicode" => "&#xe869;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Spin 2",
                "menu_icon_class" => "spin-2",
                "menu_icon_unicode" => "&#xe86a;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Spin 3",
                "menu_icon_class" => "spin-3",
                "menu_icon_unicode" => "&#xe86b;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Spin 4",
                "menu_icon_class" => "spin-4",
                "menu_icon_unicode" => "&#xe86c;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Spin 5",
                "menu_icon_class" => "spin-5",
                "menu_icon_unicode" => "&#xe86d;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Spin 6",
                "menu_icon_class" => "spin-6",
                "menu_icon_unicode" => "&#xe86e;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Firefox",
                "menu_icon_class" => "firefox",
                "menu_icon_unicode" => "&#xe86f;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Chroome",
                "menu_icon_class" => "chroome",
                "menu_icon_unicode" => "&#xe870;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Opera",
                "menu_icon_class" => "opera",
                "menu_icon_unicode" => "&#xe871;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Internet Explore",
                "menu_icon_class" => "internet-explore",
                "menu_icon_unicode" => "&#xe872;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Crown",
                "menu_icon_class" => "crown",
                "menu_icon_unicode" => "&#xe873;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Crown Plus",
                "menu_icon_class" => "crown-plus",
                "menu_icon_unicode" => "&#xe874;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Marquee",
                "menu_icon_class" => "marquee",
                "menu_icon_unicode" => "&#xe876;",
                "menu_icon_brand" => "Fontelico",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Glass",
                "menu_icon_class" => "glass",
                "menu_icon_unicode" => "&#xe877;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Music",
                "menu_icon_class" => "music",
                "menu_icon_unicode" => "&#xe877;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Search",
                "menu_icon_class" => "search",
                "menu_icon_unicode" => "&#xe879;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Mail",
                "menu_icon_class" => "mail",
                "menu_icon_unicode" => "&#xe87a;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Heart",
                "menu_icon_class" => "heart",
                "menu_icon_unicode" => "&#xe87b;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Heart Empty",
                "menu_icon_class" => "heart-empty",
                "menu_icon_unicode" => "&#xe87c;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Star",
                "menu_icon_class" => "star",
                "menu_icon_unicode" => "&#xe87d;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Star Empty",
                "menu_icon_class" => "star-empty",
                "menu_icon_unicode" => "&#xe87e;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Star Half",
                "menu_icon_class" => "star-half",
                "menu_icon_unicode" => "&#xe87f;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "User",
                "menu_icon_class" => "user",
                "menu_icon_unicode" => "&#xe880;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Users",
                "menu_icon_class" => "users",
                "menu_icon_unicode" => "&#xe880;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Video 1",
                "menu_icon_class" => "video-1",
                "menu_icon_unicode" => "&#xe882;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Videocam",
                "menu_icon_class" => "videocam",
                "menu_icon_unicode" => "&#xe883;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Picture 1",
                "menu_icon_class" => "picture-1",
                "menu_icon_unicode" => "&#xe884;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Camera",
                "menu_icon_class" => "camer",
                "menu_icon_unicode" => "&#xe885;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Camera All",
                "menu_icon_class" => "camera-all",
                "menu_icon_unicode" => "&#xe886;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "TH Large 1",
                "menu_icon_class" => "th-large-1",
                "menu_icon_unicode" => "&#xe887;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "TH 1",
                "menu_icon_class" => "th-1",
                "menu_icon_unicode" => "&#xe888;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "TH List",
                "menu_icon_class" => "th-list",
                "menu_icon_unicode" => "&#xe889;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Ok 1",
                "menu_icon_class" => "ok-1",
                "menu_icon_unicode" => "&#xe88a;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Ok Circle",
                "menu_icon_class" => "ok-circle",
                "menu_icon_unicode" => "&#xe88b;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Ok Circle 2",
                "menu_icon_class" => "ok-circle-2",
                "menu_icon_unicode" => "&#xe88c;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Cancel 1",
                "menu_icon_class" => "cancel-1",
                "menu_icon_unicode" => "&#xe88d;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Cancel Circle",
                "menu_icon_class" => "cancel-circle",
                "menu_icon_unicode" => "&#xe88e;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Plus",
                "menu_icon_class" => "plus",
                "menu_icon_unicode" => "&#xe890;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Plus Circle",
                "menu_icon_class" => "plus-circle",
                "menu_icon_unicode" => "&#xe891;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Minus",
                "menu_icon_class" => "minus",
                "menu_icon_unicode" => "&#xe892;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Minus Circle",
                "menu_icon_class" => "minus-circle",
                "menu_icon_unicode" => "&#xe893;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Help Circle",
                "menu_icon_class" => "help-circle",
                "menu_icon_unicode" => "&#xe894;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Info Circle",
                "menu_icon_class" => "info-circle",
                "menu_icon_unicode" => "&#xe895;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Home",
                "menu_icon_class" => "home",
                "menu_icon_unicode" => "&#xe896;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Link 1",
                "menu_icon_class" => "link-1",
                "menu_icon_unicode" => "&#xe897;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Attach 1",
                "menu_icon_class" => "attach-1",
                "menu_icon_unicode" => "&#xe898;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Lock 1",
                "menu_icon_class" => "lock-1",
                "menu_icon_unicode" => "&#xe899;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Lock Open",
                "menu_icon_class" => "lock-open",
                "menu_icon_unicode" => "&#xe89a;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Pin",
                "menu_icon_class" => "pin",
                "menu_icon_unicode" => "&#xe89b;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Eye",
                "menu_icon_class" => "eye",
                "menu_icon_unicode" => "&#xe89c;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Eye Off",
                "menu_icon_class" => "eye-off",
                "menu_icon_unicode" => "&#xe89d;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Tag",
                "menu_icon_class" => "tag",
                "menu_icon_unicode" => "&#xe89e;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Tags",
                "menu_icon_class" => "tags",
                "menu_icon_unicode" => "&#xe89f;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Bookmark",
                "menu_icon_class" => "bookmark",
                "menu_icon_unicode" => "&#xe8a0;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Flag",
                "menu_icon_class" => "flag",
                "menu_icon_unicode" => "&#xe8a1;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Thumb Up",
                "menu_icon_class" => "thumb-up",
                "menu_icon_unicode" => "&#xe8a2;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Thumb Down",
                "menu_icon_class" => "thumb-down",
                "menu_icon_unicode" => "&#xe8a3;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Download",
                "menu_icon_class" => "download",
                "menu_icon_unicode" => "&#xe8a4;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Upload",
                "menu_icon_class" => "upload",
                "menu_icon_unicode" => "&#xe8a5;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Forward 1",
                "menu_icon_class" => "forward-1",
                "menu_icon_unicode" => "&#xe8a6;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Export",
                "menu_icon_class" => "export",
                "menu_icon_unicode" => "&#xe8a7;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Pencil",
                "menu_icon_class" => "pencil",
                "menu_icon_unicode" => "&#xe8a8;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Edit",
                "menu_icon_class" => "edit",
                "menu_icon_unicode" => "&#xe8a9;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Print",
                "menu_icon_class" => "print",
                "menu_icon_unicode" => "&#xe8aa;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Retweet",
                "menu_icon_class" => "retweet",
                "menu_icon_unicode" => "&#xe8ab;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Comment",
                "menu_icon_class" => "comment",
                "menu_icon_unicode" => "&#xe8ac;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Chat 1",
                "menu_icon_class" => "chat-1",
                "menu_icon_unicode" => "&#xe8ad;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Bell",
                "menu_icon_class" => "bell",
                "menu_icon_unicode" => "&#xe8ae;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Attention 1",
                "menu_icon_class" => "attention-1",
                "menu_icon_unicode" => "&#xe8af;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Attention Circle",
                "menu_icon_class" => "attention-circle",
                "menu_icon_unicode" => "&#xe8b0;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Location",
                "menu_icon_class" => "location",
                "menu_icon_unicode" => "&#xe8b1;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Trash Empty",
                "menu_icon_class" => "trash-empty",
                "menu_icon_unicode" => "&#xe8b2;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Doc 1",
                "menu_icon_class" => "doc-1",
                "menu_icon_unicode" => "&#xe8b3;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Folder 1",
                "menu_icon_class" => "folder-1",
                "menu_icon_unicode" => "&#xe8b4;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Folder Open",
                "menu_icon_class" => "folder-open",
                "menu_icon_unicode" => "&#xe8b5;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Phone",
                "menu_icon_class" => "phone",
                "menu_icon_unicode" => "&#xe8b6;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Cog 1",
                "menu_icon_class" => "cog-1",
                "menu_icon_unicode" => "&#xe8b7;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Cog Alt",
                "menu_icon_class" => "cog-alt",
                "menu_icon_unicode" => "&#xe8b8;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Wrench",
                "menu_icon_class" => "wrench",
                "menu_icon_unicode" => "&#xe8b9;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Basket",
                "menu_icon_class" => "basket",
                "menu_icon_unicode" => "&#xe8ba;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Calendar",
                "menu_icon_class" => "calendar",
                "menu_icon_unicode" => "&#xe8bb;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Login",
                "menu_icon_class" => "login",
                "menu_icon_unicode" => "&#xe8bc;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Logout",
                "menu_icon_class" => "logout",
                "menu_icon_unicode" => "&#xe8bd;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Volume Off",
                "menu_icon_class" => "volume-off",
                "menu_icon_unicode" => "&#xe8be;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Volume Down",
                "menu_icon_class" => "volume-down",
                "menu_icon_unicode" => "&#xe8bf;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Volume Up",
                "menu_icon_class" => "volume-up",
                "menu_icon_unicode" => "&#xe8c0;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Handphone",
                "menu_icon_class" => "handphone",
                "menu_icon_unicode" => "&#xe8c1;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Clock",
                "menu_icon_class" => "clock",
                "menu_icon_unicode" => "&#xe8c2;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Block 1",
                "menu_icon_class" => "block-1",
                "menu_icon_unicode" => "&#xe8c3;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Resize Full 1",
                "menu_icon_class" => "resize-full-1",
                "menu_icon_unicode" => "&#xe8c4;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Resize Small",
                "menu_icon_class" => "resize-small",
                "menu_icon_unicode" => "&#xe8c5;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Resize Vertical",
                "menu_icon_class" => "resize-vertical",
                "menu_icon_unicode" => "&#xe8c6;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Resize Horizontal",
                "menu_icon_class" => "resize-horizontal",
                "menu_icon_unicode" => "&#xe8c7;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Zoom In",
                "menu_icon_class" => "zoom-in",
                "menu_icon_unicode" => "&#xe8c8;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Zoom Out",
                "menu_icon_class" => "zoom-out",
                "menu_icon_unicode" => "&#xe8c9;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Down Circle 2",
                "menu_icon_class" => "down-circle-2",
                "menu_icon_unicode" => "&#xe8ca;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Up Circle 2",
                "menu_icon_class" => "up-circle-2",
                "menu_icon_unicode" => "&#xe8cb;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Down Dir 1",
                "menu_icon_class" => "down-dir-1",
                "menu_icon_unicode" => "&#xe8cc;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Up Dir 1",
                "menu_icon_class" => "up-dir-1",
                "menu_icon_unicode" => "&#xe8cd;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Left Dir",
                "menu_icon_class" => "left-dir",
                "menu_icon_unicode" => "&#xe8ce;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Right Dir 1",
                "menu_icon_class" => "right-dir-1",
                "menu_icon_unicode" => "&#xe8cf;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Down Open",
                "menu_icon_class" => "down-open",
                "menu_icon_unicode" => "&#xe8d0;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Left Open 1",
                "menu_icon_class" => "left-open-1",
                "menu_icon_unicode" => "&#xe8d1;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Right Open 1",
                "menu_icon_class" => "right-open-1",
                "menu_icon_unicode" => "&#xe8d2;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ],
            [
                "menu_icon_name" => "Up Open",
                "menu_icon_class" => "up-open",
                "menu_icon_unicode" => "&#xe8d3;",
                "menu_icon_brand" => "Font Awesome",
                "status" => "1",
            ]
        ];

        DB::table('menu_icon')->insert($icon);
    }
}
